version: '2'

services:
  jenkins:
    image: prontotools/simplesat-jenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./credentials/aws:/root/.aws
      - ./credentials/ssh:/var/jenkins_home/.ssh
